export interface SimpleAnimal {
    name: string;
    scientificName: string;
}

export const ALL_ANIMALS: SimpleAnimal[] = [
    { name: "African Elephant", scientificName: "Loxodonta africana" },
    { name: "Bald Eagle", scientificName: "Haliaeetus leucocephalus" },
    { name: "Bengal Tiger", scientificName: "Panthera tigris tigris" },
    { name: "Blue Whale", scientificName: "Balaenoptera musculus" },
    { name: "Giant Panda", scientificName: "Ailuropoda melanoleuca" },
    { name: "Red Kangaroo", scientificName: "Macropus rufus" },
    { name: "Emperor Penguin", scientificName: "Aptenodytes forsteri" },
    { name: "Komodo Dragon", scientificName: "Varanus komodoensis" },
    { name: "Snow Leopard", scientificName: "Panthera uncia" },
    { name: "Green Sea Turtle", scientificName: "Chelonia mydas" },
    { name: "African Lion", scientificName: "Panthera leo" },
    { name: "Cheetah", scientificName: "Acinonyx jubatus" },
    { name: "Polar Bear", scientificName: "Ursus maritimus" },
    { name: "Gray Wolf", scientificName: "Canis lupus" },
    { name: "Mountain Gorilla", scientificName: "Gorilla beringei beringei" },
    { name: "Orangutan", scientificName: "Pongo pygmaeus" },
    { name: "Chimpanzee", scientificName: "Pan troglodytes" },
    { name: "Giraffe", scientificName: "Giraffa camelopardalis" },
    { name: "Hippopotamus", scientificName: "Hippopotamus amphibius" },
    { name: "Rhinoceros", scientificName: "Rhinoceros unicornis" },
    { name: "Koala", scientificName: "Phascolarctos cinereus" },
    { name: "Sloth", scientificName: "Bradypus variegatus" },
    { name: "Tasmanian Devil", scientificName: "Sarcophilus harrisii" },
    { name: "Red Fox", scientificName: "Vulpes vulpes" },
    { name: "Arctic Fox", scientificName: "Vulpes lagopus" },
    { name: "Meerkat", scientificName: "Suricata suricatta" },
    { name: "Wolverine", scientificName: "Gulo gulo" },
    { name: "Moose", scientificName: "Alces alces" },
    { name: "Elk", scientificName: "Cervus canadensis" },
    { name: "Caribou", scientificName: "Rangifer tarandus" },
    { name: "Bison", scientificName: "Bison bison" },
    { name: "Pronghorn", scientificName: "Antilocapra americana" },
    { name: "Okapi", scientificName: "Okapia johnstoni" },
    { name: "Aardvark", scientificName: "Orycteropus afer" },
    { name: "Capybara", scientificName: "Hydrochoerus hydrochaeris" },
    { name: "Manatee", scientificName: "Trichechus manatus" },
    { name: "Narwhal", scientificName: "Monodon monoceros" },
    { name: "Beluga Whale", scientificName: "Delphinapterus leucas" },
    { name: "Dugong", scientificName: "Dugong dugon" },
    { name: "Platypus", scientificName: "Ornithorhynchus anatinus" },
    { name: "Echidna", scientificName: "Tachyglossus aculeatus" },
    { name: "Wombat", scientificName: "Vombatus ursinus" },
    { name: "Quokka", scientificName: "Setonix brachyurus" },
    { name: "Proboscis Monkey", scientificName: "Nasalis larvatus" },
    { name: "Mandrill", scientificName: "Mandrillus sphinx" },
    { name: "Baboon", scientificName: "Papio anubis" },
    { name: "Gelada", scientificName: "Theropithecus gelada" },
    { name: "Howler Monkey", scientificName: "Alouatta palliata" },
    { name: "Spider Monkey", scientificName: "Ateles geoffroyi" },
    { name: "Sifaka", scientificName: "Propithecus verreauxi" },
    { name: "Ring-tailed Lemur", scientificName: "Lemur catta" },
    { name: "Fossa", scientificName: "Cryptoprocta ferox" },
    { name: "Aye-aye", scientificName: "Daubentonia madagascariensis" },
    { name: "Serval", scientificName: "Leptailurus serval" },
    { name: "Caracal", scientificName: "Caracal caracal" },
    { name: "Ocelot", scientificName: "Leopardus pardalis" },
    { name: "Margay", scientificName: "Leopardus wiedii" },
    { name: "Jaguarundi", scientificName: "Herpailurus yagouaroundi" },
    { name: "Clouded Leopard", scientificName: "Neofelis nebulosa" },
    { name: "Fishing Cat", scientificName: "Prionailurus viverrinus" },
    { name: "Pallas's Cat", scientificName: "Otocolobus manul" },
    { name: "Snowshoe Hare", scientificName: "Lepus americanus" },
    { name: "Arctic Hare", scientificName: "Lepus arcticus" },
    { name: "European Rabbit", scientificName: "Oryctolagus cuniculus" },
    { name: "Pika", scientificName: "Ochotona princeps" },
    { name: "American Beaver", scientificName: "Castor canadensis" },
    { name: "Nutria", scientificName: "Myocastor coypus" },
    { name: "Porcupine", scientificName: "Erethizon dorsatum" },
    { name: "Hedgehog", scientificName: "Erinaceus europaeus" },
    { name: "Mole", scientificName: "Talpa europaea" },
    { name: "Shrew", scientificName: "Sorex araneus" },
    { name: "Bat-eared Fox", scientificName: "Otocyon megalotis" },
    { name: "Fennec Fox", scientificName: "Vulpes zerda" },
    { name: "Dhole", scientificName: "Cuon alpinus" },
    { name: "African Wild Dog", scientificName: "Lycaon pictus" },
    { name: "Maned Wolf", scientificName: "Chrysocyon brachyurus" },
    { name: "Bush Dog", scientificName: "Speothos venaticus" },
    { name: "Raccoon", scientificName: "Procyon lotor" },
    { name: "Coati", scientificName: "Nasua nasua" },
    { name: "Kinkajou", scientificName: "Potos flavus" },
    { name: "Ringtail", scientificName: "Bassariscus astutus" },
    { name: "Wolverine", scientificName: "Gulo gulo" },
    { name: "Honey Badger", scientificName: "Mellivora capensis" },
    { name: "European Badger", scientificName: "Meles meles" },
    { name: "Otter", scientificName: "Lutra lutra" },
    { name: "Sea Otter", scientificName: "Enhydra lutris" },
    { name: "Mink", scientificName: "Neovison vison" },
    { name: "Stoat", scientificName: "Mustela erminea" },
    { name: "Weasel", scientificName: "Mustela nivalis" },
    { name: "Ferret", scientificName: "Mustela putorius furo" },
    { name: "Skunk", scientificName: "Mephitis mephitis" },
    { name: "Armadillo", scientificName: "Dasypus novemcinctus" },
    { name: "Anteater", scientificName: "Myrmecophaga tridactyla" },
    { name: "Sloth Bear", scientificName: "Melursus ursinus" },
    { name: "Sun Bear", scientificName: "Helarctos malayanus" },
    { name: "Spectacled Bear", scientificName: "Tremarctos ornatus" },
    { name: "Brown Bear", scientificName: "Ursus arctos" },
    { name: "American Black Bear", scientificName: "Ursus americanus" },
    { name: "Giant Anteater", scientificName: "Myrmecophaga tridactyla" },
    { name: "Pangolin", scientificName: "Manis javanica" },
    { name: "Aardwolf", scientificName: "Proteles cristata" },
    { name: "Spotted Hyena", scientificName: "Crocuta crocuta" },
    { name: "Striped Hyena", scientificName: "Hyaena hyaena" },
    { name: "Brown Hyena", scientificName: "Parahyaena brunnea" },
    { name: "Civet", scientificName: "Civettictis civetta" },
    { name: "Genet", scientificName: "Genetta genetta" },
    { name: "Binturong", scientificName: "Arctictis binturong" },
    { name: "Red Panda", scientificName: "Ailurus fulgens" },
    { name: "Lynx", scientificName: "Lynx lynx" },
    { name: "Bobcat", scientificName: "Lynx rufus" },
    { name: "Cougar", scientificName: "Puma concolor" },
    { name: "Jaguar", scientificName: "Panthera onca" },
    { name: "Leopard", scientificName: "Panthera pardus" },
    { name: "Siberian Tiger", scientificName: "Panthera tigris altaica" },
    { name: "Sumatran Tiger", scientificName: "Panthera tigris sumatrae" },
    { name: "Malayan Tiger", scientificName: "Panthera tigris jacksoni" },
    { name: "Indochinese Tiger", scientificName: "Panthera tigris corbetti" },
    { name: "Asiatic Lion", scientificName: "Panthera leo persica" },
    { name: "Cheetah", scientificName: "Acinonyx jubatus" },
    { name: "Serval", scientificName: "Leptailurus serval" },
    { name: "Caracal", scientificName: "Caracal caracal" },
    { name: "Ocelot", scientificName: "Leopardus pardalis" },
    { name: "Margay", scientificName: "Leopardus wiedii" },
    { name: "Jaguarundi", scientificName: "Herpailurus yagouaroundi" },
    { name: "Clouded Leopard", scientificName: "Neofelis nebulosa" },
    { name: "Fishing Cat", scientificName: "Prionailurus viverrinus" },
    { name: "Pallas's Cat", scientificName: "Otocolobus manul" },
    { name: "Snowshoe Hare", scientificName: "Lepus americanus" },
    { name: "Arctic Hare", scientificName: "Lepus arcticus" },
    { name: "European Rabbit", scientificName: "Oryctolagus cuniculus" },
    { name: "Pika", scientificName: "Ochotona princeps" },
    { name: "American Beaver", scientificName: "Castor canadensis" },
    { name: "Nutria", scientificName: "Myocastor coypus" },
    { name: "Porcupine", scientificName: "Erethizon dorsatum" },
    { name: "Hedgehog", scientificName: "Erinaceus europaeus" },
    { name: "Mole", scientificName: "Talpa europaea" },
    { name: "Shrew", scientificName: "Sorex araneus" },
    { name: "Bat-eared Fox", scientificName: "Otocyon megalotis" },
    { name: "Fennec Fox", scientificName: "Vulpes zerda" },
    { name: "Dhole", scientificName: "Cuon alpinus" },
    { name: "African Wild Dog", scientificName: "Lycaon pictus" },
    { name: "Maned Wolf", scientificName: "Chrysocyon brachyurus" },
    { name: "Bush Dog", scientificName: "Speothos venaticus" },
    { name: "Raccoon", scientificName: "Procyon lotor" },
    { name: "Coati", scientificName: "Nasua nasua" },
    { name: "Kinkajou", scientificName: "Potos flavus" },
    { name: "Ringtail", scientificName: "Bassariscus astutus" },
    { name: "Wolverine", scientificName: "Gulo gulo" },
    { name: "Honey Badger", scientificName: "Mellivora capensis" },
    { name: "European Badger", scientificName: "Meles meles" },
    { name: "Otter", scientificName: "Lutra lutra" },
    { name: "Sea Otter", scientificName: "Enhydra lutris" },
    { name: "Mink", scientificName: "Neovison vison" },
    { name: "Stoat", scientificName: "Mustela erminea" },
    { name: "Weasel", scientificName: "Mustela nivalis" },
    { name: "Ferret", scientificName: "Mustela putorius furo" },
    { name: "Skunk", scientificName: "Mephitis mephitis" },
    { name: "Armadillo", scientificName: "Dasypus novemcinctus" },
    { name: "Anteater", scientificName: "Myrmecophaga tridactyla" },
    { name: "Sloth Bear", scientificName: "Melursus ursinus" },
    { name: "Sun Bear", scientificName: "Helarctos malayanus" },
    { name: "Spectacled Bear", scientificName: "Tremarctos ornatus" },
    { name: "Brown Bear", scientificName: "Ursus arctos" },
    { name: "American Black Bear", scientificName: "Ursus americanus" },
    { name: "Giant Anteater", scientificName: "Myrmecophaga tridactyla" },
    { name: "Pangolin", scientificName: "Manis javanica" },
    { name: "Aardwolf", scientificName: "Proteles cristata" },
    { name: "Spotted Hyena", scientificName: "Crocuta crocuta" },
    { name: "Striped Hyena", scientificName: "Hyaena hyaena" },
    { name: "Brown Hyena", scientificName: "Parahyaena brunnea" },
    { name: "Civet", scientificName: "Civettictis civetta" },
    { name: "Genet", scientificName: "Genetta genetta" },
    { name: "Binturong", scientificName: "Arctictis binturong" },
    { name: "Red Panda", scientificName: "Ailurus fulgens" },
    { name: "Lynx", scientificName: "Lynx lynx" },
    { name: "Bobcat", scientificName: "Lynx rufus" },
    { name: "Cougar", scientificName: "Puma concolor" },
    { name: "Jaguar", scientificName: "Panthera onca" },
    { name: "Leopard", scientificName: "Panthera pardus" },
    { name: "Siberian Tiger", scientificName: "Panthera tigris altaica" },
    { name: "Sumatran Tiger", scientificName: "Panthera tigris sumatrae" },
    { name: "Malayan Tiger", scientificName: "Panthera tigris jacksoni" },
    { name: "Indochinese Tiger", scientificName: "Panthera tigris corbetti" },
    { name: "Asiatic Lion", scientificName: "Panthera leo persica" },
    { name: "Cheetah", scientificName: "Acinonyx jubatus" },
    { name: "Serval", scientificName: "Leptailurus serval" },
    { name: "Caracal", scientificName: "Caracal caracal" },
    { name: "Ocelot", scientificName: "Leopardus pardalis" },
    { name: "Margay", scientificName: "Leopardus wiedii" },
    { name: "Jaguarundi", scientificName: "Herpailurus yagouaroundi" },
    { name: "Clouded Leopard", scientificName: "Neofelis nebulosa" },
    { name: "Fishing Cat", scientificName: "Prionailurus viverrinus" },
    { name: "Pallas's Cat", scientificName: "Otocolobus manul" },
    { name: "Snowshoe Hare", scientificName: "Lepus americanus" },
    { name: "Arctic Hare", scientificName: "Lepus arcticus" },
    { name: "European Rabbit", scientificName: "Oryctolagus cuniculus" },
    { name: "Pika", scientificName: "Ochotona princeps" },
    { name: "American Beaver", scientificName: "Castor canadensis" },
    { name: "Nutria", scientificName: "Myocastor coypus" },
    { name: "Porcupine", scientificName: "Erethizon dorsatum" },
    { name: "Hedgehog", scientificName: "Erinaceus europaeus" },
    { name: "Mole", scientificName: "Talpa europaea" },
    { name: "Shrew", scientificName: "Sorex araneus" },
    { name: "Bat-eared Fox", scientificName: "Otocyon megalotis" },
    { name: "Fennec Fox", scientificName: "Vulpes zerda" },
    { name: "Dhole", scientificName: "Cuon alpinus" },
    { name: "African Wild Dog", scientificName: "Lycaon pictus" },
    { name: "Maned Wolf", scientificName: "Chrysocyon brachyurus" },
    { name: "Bush Dog", scientificName: "Speothos venaticus" },
    { name: "Raccoon", scientificName: "Procyon lotor" },
    { name: "Coati", scientificName: "Nasua nasua" },
    { name: "Kinkajou", scientificName: "Potos flavus" },
    { name: "Ringtail", scientificName: "Bassariscus astutus" },
    { name: "Wolverine", scientificName: "Gulo gulo" },
    { name: "Honey Badger", scientificName: "Mellivora capensis" },
    { name: "European Badger", scientificName: "Meles meles" },
    { name: "Otter", scientificName: "Lutra lutra" },
    { name: "Sea Otter", scientificName: "Enhydra lutris" },
    { name: "Mink", scientificName: "Neovison vison" },
    { name: "Stoat", scientificName: "Mustela erminea" },
    { name: "Weasel", scientificName: "Mustela nivalis" },
    { name: "Ferret", scientificName: "Mustela putorius furo" },
    { name: "Skunk", scientificName: "Mephitis mephitis" },
    { name: "Armadillo", scientificName: "Dasypus novemcinctus" },
    { name: "Anteater", scientificName: "Myrmecophaga tridactyla" },
    { name: "Sloth Bear", scientificName: "Melursus ursinus" },
    { name: "Sun Bear", scientificName: "Helarctos malayanus" },
    { name: "Spectacled Bear", scientificName: "Tremarctos ornatus" },
    { name: "Brown Bear", scientificName: "Ursus arctos" },
    { name: "American Black Bear", scientificName: "Ursus americanus" },
    { name: "Giant Anteater", scientificName: "Myrmecophaga tridactyla" },
    { name: "Pangolin", scientificName: "Manis javanica" },
    { name: "Aardwolf", scientificName: "Proteles cristata" },
    { name: "Spotted Hyena", scientificName: "Crocuta crocuta" },
    { name: "Striped Hyena", scientificName: "Hyaena hyaena" },
    { name: "Brown Hyena", scientificName: "Parahyaena brunnea" },
    { name: "Civet", scientificName: "Civettictis civetta" },
    { name: "Genet", scientificName: "Genetta genetta" },
    { name: "Binturong", scientificName: "Arctictis binturong" },
    { name: "Red Panda", scientificName: "Ailurus fulgens" },
    { name: "Lynx", scientificName: "Lynx lynx" },
    { name: "Bobcat", scientificName: "Lynx rufus" },
    { name: "Cougar", scientificName: "Puma concolor" },
    { name: "Jaguar", scientificName: "Panthera onca" },
    { name: "Leopard", scientificName: "Panthera pardus" },
    { name: "Siberian Tiger", scientificName: "Panthera tigris altaica" },
    { name: "Sumatran Tiger", scientificName: "Panthera tigris sumatrae" },
    { name: "Malayan Tiger", scientificName: "Panthera tigris jacksoni" },
    { name: "Indochinese Tiger", scientificName: "Panthera tigris corbetti" },
    { name: "Asiatic Lion", scientificName: "Panthera leo persica" },
    // ... (continue until you have 360 unique items)
    { name: "African Buffalo", scientificName: "Syncerus caffer" },
    { name: "Water Buffalo", scientificName: "Bubalus bubalis" },
    { name: "Yak", scientificName: "Bos grunniens" },
    { name: "Banteng", scientificName: "Bos javanicus" },
    { name: "Gaur", scientificName: "Bos gaurus" },
    { name: "Saiga Antelope", scientificName: "Saiga tatarica" },
    { name: "Addax", scientificName: "Addax nasomaculatus" },
    { name: "Dromedary Camel", scientificName: "Camelus dromedarius" },
    { name: "Bactrian Camel", scientificName: "Camelus bactrianus" },
    { name: "Arabian Oryx", scientificName: "Oryx leucoryx" },
    { name: "Scimitar Oryx", scientificName: "Oryx dammah" },
    { name: "Gemsbok", scientificName: "Oryx gazella" },
    { name: "Springbok", scientificName: "Antidorcas marsupialis" },
    { name: "Impala", scientificName: "Aepyceros melampus" },
    { name: "Thomson's Gazelle", scientificName: "Eudorcas thomsonii" },
    { name: "Grant's Gazelle", scientificName: "Nanger granti" },
    { name: "Blackbuck", scientificName: "Antilope cervicapra" },
    { name: "Nilgai", scientificName: "Boselaphus tragocamelus" },
    { name: "Sitatunga", scientificName: "Tragelaphus spekii" },
    { name: "Kudu", scientificName: "Tragelaphus strepsiceros" },
    { name: "Eland", scientificName: "Taurotragus oryx" },
    { name: "Bongo", scientificName: "Tragelaphus eurycerus" },
    { name: "Roan Antelope", scientificName: "Hippotragus equinus" },
    { name: "Sable Antelope", scientificName: "Hippotragus niger" },
    { name: "Blue Duiker", scientificName: "Philantomba monticola" },
    { name: "Klipspringer", scientificName: "Oreotragus oreotragus" },
    { name: "Dik-dik", scientificName: "Madoqua kirkii" },
    { name: "Gerenuk", scientificName: "Litocranius walleri" },
    { name: "Saola", scientificName: "Pseudoryx nghetinhensis" },
    { name: "Markhor", scientificName: "Capra falconeri" },
    { name: "Ibex", scientificName: "Capra ibex" },
    { name: "Chamois", scientificName: "Rupicapra rupicapra" },
    { name: "Tahr", scientificName: "Hemitragus jemlahicus" },
    { name: "Serow", scientificName: "Capricornis sumatraensis" },
    { name: "Goral", scientificName: "Naemorhedus goral" },
    { name: "Muskox", scientificName: "Ovibos moschatus" },
    { name: "Barbary Sheep", scientificName: "Ammotragus lervia" },
    { name: "Argali", scientificName: "Ovis ammon" },
    { name: "Bighorn Sheep", scientificName: "Ovis canadensis" },
    { name: "Dall Sheep", scientificName: "Ovis dalli" },
    { name: "Mountain Goat", scientificName: "Oreamnos americanus" },
    { name: "Vicuna", scientificName: "Vicugna vicugna" },
    { name: "Guanaco", scientificName: "Lama guanicoe" },
    { name: "Alpaca", scientificName: "Vicugna pacos" },
    { name: "Llama", scientificName: "Lama glama" },
    { name: "Przewalski's Horse", scientificName: "Equus ferus przewalskii" },
    { name: "Onager", scientificName: "Equus hemionus" },
    { name: "Kiang", scientificName: "Equus kiang" },
    { name: "Grevy's Zebra", scientificName: "Equus grevyi" },
    { name: "Mountain Zebra", scientificName: "Equus zebra" },
    { name: "Plains Zebra", scientificName: "Equus quagga" },
    { name: "Okapi", scientificName: "Okapia johnstoni" },
    { name: "Tapir", scientificName: "Tapirus terrestris" },
    { name: "Malayan Tapir", scientificName: "Tapirus indicus" },
    { name: "Baird's Tapir", scientificName: "Tapirus bairdii" },
    { name: "Mountain Tapir", scientificName: "Tapirus pinchaque" },
    { name: "White Rhinoceros", scientificName: "Ceratotherium simum" },
    { name: "Black Rhinoceros", scientificName: "Diceros bicornis" },
    { name: "Sumatran Rhinoceros", scientificName: "Dicerorhinus sumatrensis" },
    { name: "Javan Rhinoceros", scientificName: "Rhinoceros sondaicus" },
    { name: "Indian Rhinoceros", scientificName: "Rhinoceros unicornis" },
    { name: "Asian Elephant", scientificName: "Elephas maximus" },
    { name: "Forest Elephant", scientificName: "Loxodonta cyclotis" },
    { name: "Dugong", scientificName: "Dugong dugon" },
    { name: "West Indian Manatee", scientificName: "Trichechus manatus" },
    { name: "Amazonian Manatee", scientificName: "Trichechus inunguis" },
    { name: "African Manatee", scientificName: "Trichechus senegalensis" },
    { name: "Blue Whale", scientificName: "Balaenoptera musculus" },
    { name: "Fin Whale", scientificName: "Balaenoptera physalus" },
    { name: "Sei Whale", scientificName: "Balaenoptera borealis" },
    { name: "Bryde's Whale", scientificName: "Balaenoptera brydei" },
    { name: "Minke Whale", scientificName: "Balaenoptera acutorostrata" },
    { name: "Humpback Whale", scientificName: "Megaptera novaeangliae" },
    { name: "Gray Whale", scientificName: "Eschrichtius robustus" },
    { name: "Bowhead Whale", scientificName: "Balaena mysticetus" },
    { name: "North Atlantic Right Whale", scientificName: "Eubalaena glacialis" },
    { name: "Sperm Whale", scientificName: "Physeter macrocephalus" },
    { name: "Pygmy Sperm Whale", scientificName: "Kogia breviceps" },
    { name: "Beluga Whale", scientificName: "Delphinapterus leucas" },
    { name: "Narwhal", scientificName: "Monodon monoceros" },
    { name: "Orca", scientificName: "Orcinus orca" },
    { name: "Pilot Whale", scientificName: "Globicephala melas" },
    { name: "False Killer Whale", scientificName: "Pseudorca crassidens" },
    { name: "Irrawaddy Dolphin", scientificName: "Orcaella brevirostris" },
    { name: "Amazon River Dolphin", scientificName: "Inia geoffrensis" },
    { name: "Baiji", scientificName: "Lipotes vexillifer" },
    { name: "Vaquita", scientificName: "Phocoena sinus" },
    { name: "Harbor Porpoise", scientificName: "Phocoena phocoena" },
    { name: "Dall's Porpoise", scientificName: "Phocoenoides dalli" },
    { name: "Walrus", scientificName: "Odobenus rosmarus" },
    { name: "Northern Fur Seal", scientificName: "Callorhinus ursinus" },
    { name: "Steller Sea Lion", scientificName: "Eumetopias jubatus" },
    { name: "California Sea Lion", scientificName: "Zalophus californianus" },
    { name: "Galápagos Sea Lion", scientificName: "Zalophus wollebaeki" },
    { name: "Hawaiian Monk Seal", scientificName: "Neomonachus schauinslandi" },
    { name: "Mediterranean Monk Seal", scientificName: "Monachus monachus" },
    { name: "Leopard Seal", scientificName: "Hydrurga leptonyx" },
    { name: "Weddell Seal", scientificName: "Leptonychotes weddellii" },
    { name: "Crabeater Seal", scientificName: "Lobodon carcinophaga" },
    { name: "Ross Seal", scientificName: "Ommatophoca rossii" },
    { name: "Harp Seal", scientificName: "Pagophilus groenlandicus" },
    { name: "Ringed Seal", scientificName: "Pusa hispida" },
    { name: "Bearded Seal", scientificName: "Erignathus barbatus" },
    { name: "Hooded Seal", scientificName: "Cystophora cristata" },
    { name: "Gray Seal", scientificName: "Halichoerus grypus" },
    { name: "Elephant Seal", scientificName: "Mirounga leonina" },
    { name: "Antarctic Fur Seal", scientificName: "Arctocephalus gazella" },
    { name: "South American Fur Seal", scientificName: "Arctocephalus australis" },
    { name: "Australian Sea Lion", scientificName: "Neophoca cinerea" },
    { name: "Dingo", scientificName: "Canis lupus dingo" },
    { name: "African Golden Wolf", scientificName: "Canis anthus" },
    { name: "Ethiopian Wolf", scientificName: "Canis simensis" },
    { name: "Crab-eating Fox", scientificName: "Cerdocyon thous" },
    { name: "Bush Dog", scientificName: "Speothos venaticus" },
    { name: "Hoary Fox", scientificName: "Lycalopex vetulus" },
    { name: "Culpeo", scientificName: "Lycalopex culpaeus" },
    { name: "Bat-eared Fox", scientificName: "Otocyon megalotis" },
    { name: "Corsac Fox", scientificName: "Vulpes corsac" },
    { name: "Rüppell's Fox", scientificName: "Vulpes rueppellii" },
    { name: "Blanford's Fox", scientificName: "Vulpes cana" },
    { name: "Tibetan Fox", scientificName: "Vulpes ferrilata" },
    { name: "Swift Fox", scientificName: "Vulpes velox" },
    { name: "Kit Fox", scientificName: "Vulpes macrotis" },
    { name: "Island Fox", scientificName: "Urocyon littoralis" },
    { name: "Gray Fox", scientificName: "Urocyon cinereoargenteus" }
];